### ISSUE TITLE
Configure CI for the hugo website

### ISSUE THREAD

**Issue by yochannah** [codeisscience/code-is-science#20]
This site is powered by hugo. Let's configure continuous integration so we don't have to build manually before deploying. 

Possible guidelines: https://www.metachris.com/2017/04/continuous-deployment-hugo---travis-ci--github-pages/

**Comment by JJ** [comment]
You can do that by configuring a token in Travis (or wherever), or locally by creating a post-commit hook. I can do the second, although it will have to be installed by hand by linking it from the .git/hooks directory.

**Comment by yochannah** [comment]
feel free to pick this up! <3

**Comment by yochannah** [comment]
whoops, that label was a slip of the finger. This is _not_ a first timers issue!

**Comment by JJ** [comment]
What do you want to do in Travis? Check spelling, for instance?

**Comment by yochannah** [comment]
So I didn't quite understand how the post-commit hook works - I was assuming that it would run on travis (even though you did say above it ran locally!). The hook is great but it doesn't stop people from accidentally commiting changes that won't be reflected on the website.

We have two things we could configure for travis

- [ ] build hugo and push to the repo
- [ ] build the r script in this pr: https://github.com/yochannah/code-is-science/pull/33

**Comment by JJ** [comment]
El vie., 11 may. 2018 a las 12:55, Yo Yehudi (<notifications@github.com>)
escribió:

> So I didn't quite understand how the post-commit hook works - I was
> assuming that it would run on travis (even though you did say above it ran
> locally!). The hook is great but it doesn't stop people from accidentally
> commiting changes that won't be reflected on the website.
>

When you install it locally, it automatically runs Hugo.

> We have two things we could configure for travis
>
>    - build hugo and push to the repo
>
> That's that the post-commit hook does. Well, it does not push, but it
builds, then you can commit and push. Commit can also be done automatically
with some standard message, if needed.

**Comment by yochannah** [comment]
committing with a standard message (and maybe even push) would be brilliant!

**Comment by ha0ye** [comment]
Sounds like the `post-commit` hook is for running hugo locally on each commit, such that the website files get updated and included?

The common Travis CI configurations I've seen generate the website files and push them to a different branch, which GitHub Pages (or another service) then uses for the website. Is that where this issue is headed?

**Comment by yochannah** [comment]
@ha0ye ideally, yes - that way someone who doesn't have hugo on their
machine could still update the site

**Comment by JJ** [comment]
@ha0ye that's correct, that's what it does. 
@yochannah if you want Travis to update stuff for you this can still be used, but let's look at several scenarios here.
* In the first one, you have to set up your GitHub API key in Travis so that Travis can write to your repo. Then every time someone with push access to the repo does that, Travis pushes back to GitHub . That implies setting up the operation in Travis: you do have the repo there, but if I'm not wrong not the whole history, probably that is not needed, but you will definitely have Hugo installed, no big deal either, but you need to have a Go configuration... Which prevents Travis, or at least makes it more difficult, to run any other kind of tests... Besides, it's making a push to Hugo for every commit, and you might not want to have that. In some cases, that might be slow and you might have to be waiting for the next changes to be done. Then, someone with write access might actually have Hugo installed, and you will have to check out whether you actually need to run it... baseline is: uploaded API key, complicated Travis configuration, might not be needed after all, because if someone with push access can't install Hugo, next one can do it probably.
* Second scenario are pull requests. These PRs can't access local configuration and env variables for security reasons. No big deal, because when you actually accept the PR it's a push and then you do have permission...
* Third scenario is people without write access before the pull request. They will either have to set up Hugo locally or else upload their API key so that their Travis account publishes to their repo... And that might imply to change the Travis tooling to work on _their_ repo...

Baseline is: putting Travis in the loop which, as far as I understand it, is already going to take care of generating a table from Google Drive, is going to too much trouble when you can simply have one or two persons with write access to have Hugo installed, even automatically running as a post-commit hook, and do a @-message in a commit message to do the page generation for you, I guess. 
You save going to the command line when accepting PRs to generate the pages again, but you will have to create instead some complicated tooling... 

Anyway, your call. Also take into account that other sites, like Shippable or Circle-CI, are kinda better to do this kind of continuous delivery, so maybe several of them could be set up, one for each task...
